---
- name: Test playbook for nvm role
  hosts: all
  connection: local
  become: yes

  roles:
  - role: nvm
    nvm:
      version: v0.33
      node_version: '8.11.3'
  - role: npm-modules
    node_version: '8.11.3'
